/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDto } from './audit-dto';
import { MoneyDto } from './money-dto';
import { CompanyPositionDto } from './company-position-dto';


export interface CompanyPricingProfileDto { 
    id: string;
    name: string;
    position: CompanyPositionDto;
    hourlyRate: MoneyDto;
    audit: AuditDto;
}

