/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionalMoneyDto } from './optional-money-dto';


export interface CreateProjectPricingDto { 
    type: CreateProjectPricingDtoTypeEnum | null;
    hourlyRate: OptionalMoneyDto;
    fixedPrice: OptionalMoneyDto;
}
export enum CreateProjectPricingDtoTypeEnum {
    FixedPrice = 'fixed_price',
    TimeAndMaterial = 'time_and_material'
};



