/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateProjectInfoDto } from './create-project-info-dto';
import { CreateProjectTimelineDto } from './create-project-timeline-dto';
import { CreateProjectPricingDto } from './create-project-pricing-dto';


export interface CreateProjectDto { 
    info: CreateProjectInfoDto;
    timeline: CreateProjectTimelineDto;
    pricing: CreateProjectPricingDto;
}

