/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum DocumentTypeEnum {
    EmploymentAgreement = 'employment_agreement',
    Amendment = 'amendment',
    IndependentContractorAgreement = 'independent_contractor_agreement',
    MasterServiceAgreement = 'master_service_agreement',
    NonDisclosureAgreement = 'non_disclosure_agreement',
    NonCompeteAgreement = 'non_compete_agreement',
    PartnershipAgreement = 'partnership_agreement',
    StatementOfWork = 'statement_of_work',
    SecurityAndPrivacyAddendum = 'security_and_privacy_addendum',
    TerminationNotice = 'termination_notice'
};

