/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDto } from './audit-dto';
import { FiscalYearTypeEnum } from './fiscal-year-type-enum';
import { AnnualEmployeeSheetDto } from './annual-employee-sheet-dto';


export interface FiscalYearDto { 
    type: FiscalYearTypeEnum;
    id: string;
    startDate: string;
    endDate: string;
    annualEmployeeSheets: Array<AnnualEmployeeSheetDto>;
    audit: AuditDto;
}

