/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ProjectStatusEnum {
    Draft = 'draft',
    InProgress = 'in_progress',
    OnHold = 'on_hold',
    Maintenance = 'maintenance',
    Completed = 'completed',
    Canceled = 'canceled'
};

