/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDto } from './audit-dto';
import { EmploymentInfoDto } from './employment-info-dto';
import { PersonalInfoDto } from './personal-info-dto';
import { AccountDto } from './account-dto';


export interface UserDto { 
    id: string;
    account: AccountDto;
    personalInfo: PersonalInfoDto;
    employmentInfo: EmploymentInfoDto;
    audit: AuditDto;
}

