/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDto } from './audit-dto';
import { VacationTypeEnum } from './vacation-type-enum';
import { VacationStatusEnum } from './vacation-status-enum';
import { AnnualEmployeeSheetDto } from './annual-employee-sheet-dto';


export interface VacationDto { 
    type: VacationTypeEnum;
    status: VacationStatusEnum;
    id: string;
    reason?: string | null;
    fromDate: string;
    toDate: string;
    workingDays: number;
    approved: boolean;
    annualEmployeeSheet: AnnualEmployeeSheetDto;
    audit: AuditDto;
}

