/**
 * Altamira Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './project-dto';
import { WorkLogRecurrenceDto } from './work-log-recurrence-dto';
import { UserDto } from './user-dto';


export interface WorkLogDto { 
    id: string;
    minutesLogged: number;
    date: string;
    description: string | null;
    user: UserDto | null;
    userFullName: string;
    project: ProjectDto | null;
    projectName: string;
    recurrence: WorkLogRecurrenceDto | null;
}

